/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    updates: Update;
    campaigns: Campaign;
    'team-members': TeamMember;
    testimonials: Testimonial;
    media: Media;
    'form-submissions': FormSubmission;
    donations: Donation;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    updates: UpdatesSelect<false> | UpdatesSelect<true>;
    campaigns: CampaignsSelect<false> | CampaignsSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    donations: DonationsSelect<false> | DonationsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  /**
   * Leave blank to generate from the title. Changing this breaks existing links.
   */
  slug?: string | null;
  hero?: {
    image?: (string | null) | Media;
    subtitle?: string | null;
  };
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Overrides the defaults. Leave blank to derive from the title and hero.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Describe the image for screen readers. Required — WCAG AA is a launch gate (PRD §11).
   */
  alt: string;
  /**
   * Photographer or source, if attribution is needed.
   */
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "updates".
 */
export interface Update {
  id: string;
  title: string;
  /**
   * Leave blank to generate from the title. Changing this breaks existing links.
   */
  slug?: string | null;
  date: string;
  category: 'outreach' | 'partnership' | 'campaign';
  author?: (string | null) | User;
  coverImage?: (string | null) | Media;
  /**
   * Shown in listings and as the social share description.
   */
  excerpt?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * For press coverage hosted elsewhere. If set, listings link out instead of to a detail page.
   */
  externalSource?: {
    url?: string | null;
    publication?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  /**
   * Admin is reserved for the sole maintainer. Lead Editors may assign Editor, Contributor, or Viewer only.
   */
  role: 'admin' | 'leadEditor' | 'editor' | 'contributor' | 'viewer';
  /**
   * Uncheck to revoke access without deleting the account or its history.
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Fundraising campaigns. Create one here and its page publishes automatically at /campaigns/<slug> — no developer needed.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "campaigns".
 */
export interface Campaign {
  id: string;
  title: string;
  /**
   * Leave blank to generate from the title. Changing this breaks existing links.
   */
  slug?: string | null;
  status: 'active' | 'completed';
  /**
   * Target in Ghana cedis (GHS). Whole cedis — no decimals.
   */
  goalAmount: number;
  /**
   * Calculated from donation records. Not editable by anyone, by design.
   */
  raisedAmount?: number | null;
  /**
   * One or two sentences, used in listings and social shares.
   */
  summary: string;
  heroImage?: (string | null) | Media;
  story: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Structured so the breakdown renders as a consistent table regardless of who authors it.
   */
  budgetBreakdown?:
    | {
        item: string;
        /**
         * Ghana cedis (GHS).
         */
        amount: number;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  gallery?:
    | {
        image: string | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: string;
  name: string;
  role: string;
  /**
   * Optional. Members without a photo fall back to a designed initials avatar, not a stock silhouette.
   */
  photo?: (string | null) | Media;
  bio?: string | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  links?: {
    linkedin?: string | null;
    twitter?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Ships empty. Publish only real, attributable quotes — an empty section is honest, an invented testimonial is not (PRD §10).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: string;
  quote: string;
  attribution: string;
  /**
   * e.g. "Volunteer nurse, Blue Mission"
   */
  role?: string | null;
  photo?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: string;
  formType: 'volunteer' | 'membership' | 'partnership';
  name: string;
  email: string;
  phone?: string | null;
  organization?: string | null;
  occupation?: string | null;
  availability?: string | null;
  areaOfInterest?: string | null;
  partnershipType?: string | null;
  message?: string | null;
  /**
   * Mark once someone has followed up.
   */
  handled?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Financial records. Card and mobile money entries are written by the Paystack webhook; offline gifts are recorded here by hand.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donations".
 */
export interface Donation {
  id: string;
  /**
   * Paystack transaction reference, or a generated one for offline gifts.
   */
  reference: string;
  /**
   * Amount in pesewas (GHS × 100), matching what Paystack sends. 50 cedis is 5000.
   */
  amount: number;
  currency: string;
  status: 'pending' | 'success' | 'failed';
  /**
   * Only live records count toward public totals. Test-mode traffic can never inflate a campaign.
   */
  mode: 'live' | 'test';
  source: 'paystack' | 'offline';
  /**
   * Leave blank for a general donation. Only campaign-attributed gifts move a progress bar.
   */
  campaign?: (string | null) | Campaign;
  paidAt?: string | null;
  /**
   * Optional. Only collect what is needed for reconciliation.
   */
  donorName?: string | null;
  /**
   * Optional. Never displayed publicly.
   */
  donorEmail?: string | null;
  /**
   * For offline gifts — e.g. the bank reference or what was donated.
   */
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'updates';
        value: string | Update;
      } | null)
    | ({
        relationTo: 'campaigns';
        value: string | Campaign;
      } | null)
    | ({
        relationTo: 'team-members';
        value: string | TeamMember;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: string | Testimonial;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: string | FormSubmission;
      } | null)
    | ({
        relationTo: 'donations';
        value: string | Donation;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  hero?:
    | T
    | {
        image?: T;
        subtitle?: T;
      };
  body?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "updates_select".
 */
export interface UpdatesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  date?: T;
  category?: T;
  author?: T;
  coverImage?: T;
  excerpt?: T;
  body?: T;
  externalSource?:
    | T
    | {
        url?: T;
        publication?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "campaigns_select".
 */
export interface CampaignsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  goalAmount?: T;
  raisedAmount?: T;
  summary?: T;
  heroImage?: T;
  story?: T;
  budgetBreakdown?:
    | T
    | {
        item?: T;
        amount?: T;
        note?: T;
        id?: T;
      };
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  photo?: T;
  bio?: T;
  order?: T;
  links?:
    | T
    | {
        linkedin?: T;
        twitter?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  attribution?: T;
  role?: T;
  photo?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  formType?: T;
  name?: T;
  email?: T;
  phone?: T;
  organization?: T;
  occupation?: T;
  availability?: T;
  areaOfInterest?: T;
  partnershipType?: T;
  message?: T;
  handled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donations_select".
 */
export interface DonationsSelect<T extends boolean = true> {
  reference?: T;
  amount?: T;
  currency?: T;
  status?: T;
  mode?: T;
  source?: T;
  campaign?: T;
  paidAt?: T;
  donorName?: T;
  donorEmail?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Organisation-wide settings. Admin only.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  orgName: string;
  tagline?: string | null;
  vision?: string | null;
  mission?: string | null;
  /**
   * Shown on the home page. Confirm point-in-time figures with PAIF before publishing — see PRD §2.1.
   */
  impactCounters?:
    | {
        label: string;
        value: number;
        /**
         * Optional qualifier, e.g. "as of 2024". Use for figures that are point-in-time rather than cumulative.
         */
        asOf?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * PAIF operates from two offices — Italy and Ghana (PRD §1).
   */
  offices?:
    | {
        name: string;
        addressLines: string;
        phone?: string | null;
        hours?: string | null;
        mapUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  social?: {
    facebook?: string | null;
    instagram?: string | null;
    twitter?: string | null;
    linkedin?: string | null;
  };
  /**
   * Drives the home page campaign highlight.
   */
  featuredCampaign?: (string | null) | Campaign;
  featuredUpdate?: (string | null) | Update;
  /**
   * Master switch (PRD §10). When OFF: every donate CTA disappears, /donate returns 404 and is dropped from the sitemap, and campaign progress bars hide. Defaults to OFF so the site cannot accidentally launch soliciting donations it cannot receive. Turn ON only once the Paystack live account is verified.
   */
  donationsEnabled?: boolean | null;
  /**
   * e.g. "GHS 50 funds a market health screening." Shown near the donate button.
   */
  impactFraming?: string | null;
  /**
   * Shown on the donate page as an alternative to card payment.
   */
  bankTransferDetails?: string | null;
  /**
   * Paystack's processing fee, as a percentage. Used only for the optional 'cover the transaction fee' checkbox. Editable because processor rates change — confirm the current Ghana rate in your Paystack dashboard rather than trusting this default.
   */
  feePercent?: number | null;
  /**
   * Maximum fee in pesewas (GHS × 100). Paystack caps local fees; 10000 = GHS 100. Set to 0 for no cap.
   */
  feeCapPesewas?: number | null;
  /**
   * Where volunteer, membership, and partnership submissions are sent. Editable here so it can change without a deploy.
   */
  notificationEmail?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  orgName?: T;
  tagline?: T;
  vision?: T;
  mission?: T;
  impactCounters?:
    | T
    | {
        label?: T;
        value?: T;
        asOf?: T;
        id?: T;
      };
  offices?:
    | T
    | {
        name?: T;
        addressLines?: T;
        phone?: T;
        hours?: T;
        mapUrl?: T;
        id?: T;
      };
  social?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        twitter?: T;
        linkedin?: T;
      };
  featuredCampaign?: T;
  featuredUpdate?: T;
  donationsEnabled?: T;
  impactFraming?: T;
  bankTransferDetails?: T;
  feePercent?: T;
  feeCapPesewas?: T;
  notificationEmail?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}